### ISSUE TITLE
大佬, hook wx 704的一个方法会报错

### ISSUE THREAD

**Issue by 18712886438** [WaterlooBridge/EdXposed#3]
```java
findAndHookMethod("com.tencent.mm.compatible.e.q", classLoader, "bH", boolean.class, new XC_MethodHook() {});
```

```java
     
at android.base.WhaleRuntime.handleHookedMethod(WhaleRuntime.java:51)
        at android.content.ContextWrapper.attachBaseContext(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:162)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5726)
        at com.zhenl.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:85)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6505)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at com.tencent.mm.sdk.platformtools.au.<init>(SourceFile:40)
        at com.tencent.mm.compatible.e.q.<clinit>(SourceFile:70)
```

**Comment by 18712886438** [comment]
额, 再补充一下 是通过勾ContextWrapper.class, "attachBaseContext"方法拿的classloader

**Comment by WaterlooBridge** [comment]
因为静态方法是lazy resolved，所以在hook前需要确保方法已经resolved，这就导致静态方法对应的类需要先加载，对应的静态代码块就会被执行。com.tencent.mm.compatible.e.q的静态代码块里面创建了au对象，而au的构造方法里面又引用到了ah的context，此时ah的context为null，所以……
暂时还没有想到好的解决方案，你可以先hook一下com.tencent.mm.sdk.platformtools.ah的setContext方法，在setContext执行之后再去hook com.tencent.mm.compatible.e.q

**Comment by 18712886438** [comment]
> 因为静态方法是lazy resolved，所以在hook前需要确保方法已经resolved，这就导致静态方法对应的类需要先加载，对应的静态代码块就会被执行。com.tencent.mm.compatible.e.q的静态代码块里面创建了au对象，而au的构造方法里面又引用到了ah的context，此时ah的context为null，所以……
> 暂时还没有想到好的解决方案，你可以先hook一下com.tencent.mm.sdk.platformtools.ah的setContext方法，在setContext执行之后再去hook com.tencent.mm.compatible.e.q

哦哦,原来如此,感谢大佬解答
