### ISSUE TITLE
Unable to read data from libart.so.

### ISSUE THREAD

**Issue by minoism** [WaterlooBridge/EdXposed#5]
将 EdXposed-Whale 植入 App 时报错
```java
2020-07-15 10:48:27.373 11483-11483/com.erin.hooking E/Whale: Unable to read data from libart.so.
2020-07-15 10:48:27.373 11483-11483/com.erin.hooking E/Whale: Runtime setup failed
2020-07-15 10:48:27.374 11483-11483/com.erin.hooking E/Mars-Xposed: error during Xposed initialization
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.erin.hooking-t1n3ZOB4dChylBs-oKN-_Q==/lib/arm64/libwhale.mars.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
```

**Device:**
> OnePlus 7 Pro (GM1910)
> Android 10

**Comment by WaterlooBridge** [comment]
Sorry，今天刚看到你提的issue，我已经在whale中修改了libart.so的查找逻辑，但是没有移植到这个项目，你可以参考这个commit
https://github.com/WaterlooBridge/whale/commit/0c5058e1736f67c56330d8e98711f05dece1c0ee
>

**Comment by minoism** [comment]
thx
